module: TraceLog
author: Tony Stone
author_url: http://github.com/tonystone
github_url: http://github.com/tonystone/tracelog
readme: ./README.md
exclude:
  - "Tests/**/*.swift"
  - "Sources/**/Environment.swift"
  - "Sources/**/Result.swift"

copyright: '© 2019 [Tony Stone](https://github.com/tonystone) under the [Apache License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0.html).'

xcodebuild_arguments: [clean,build,-project,TraceLog.xcodeproj,-scheme,TraceLog-Package]

theme: fullwidth

documentation: Documentation/*.md
abstract: Documentation/Abstracts/*.md

output: docs

custom_categories:
  - name: User Guides
    children:
      - Quick Start
      - Configuration
      - Logging
  - name: Writers
    children:
      - ConsoleWriter
      - FileWriter
  - name: Formatters
    children:
      - TextFormat
      - JSONFormat
  - name: Global Configuration
    children:
      - LogLevel
      - ConcurrencyMode
      - WriterConcurrencyMode
      - AsyncOption
  - name: Software Developer Kit (SDK)
    children:
      - Writer
      - OutputStreamWriter
      - OutputStreamFormatter
      - StaticContext
      - RuntimeContext
      - OutputStreamFormatterError
      - FailureReason


