language: objective-c
os: osx
osx_image: xcode8

before_install:
    - gem install xcpretty -N --no-ri --no-rdoc

env:
    matrix:
        - SCHEME=TraceLog-iOS-Example TEST_DEST="platform=iOS Simulator,OS=10.0,name=iPhone 6s" TEST_SDK=iphonesimulator
        - SCHEME=TraceLog-iOS-Example TEST_DEST="platform=iOS Simulator,OS=10.0,name=iPhone 6" TEST_SDK=iphonesimulator
        - SCHEME=TraceLog-iOS-Example TEST_DEST="platform=iOS Simulator,OS=9.3,name=iPhone 6" TEST_SDK=iphonesimulator
        - SCHEME=TraceLog-iOS-Example TEST_DEST="platform=iOS Simulator,OS=9.2,name=iPhone 5s" TEST_SDK=iphonesimulator
        - SCHEME=TraceLog-iOS-Example TEST_DEST="platform=iOS Simulator,OS=9.0,name=iPhone 4s" TEST_SDK=iphonesimulator
        - SCHEME=TraceLog-OSX-Example TEST_DEST="platform=OS X,arch=x86_64" TEST_SDK=macosx

script:
    - set -o pipefail
    - xcodebuild clean test -workspace Example/TraceLog.xcworkspace -scheme "$SCHEME" -destination "$TEST_DEST" -sdk "$TEST_SDK" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)
