language: objective-c
xcode_workspace: Example/TraceLog.xcworkspace
xcode_scheme: TraceLog-Example
osx_image: xcode7.2

before_install:
    - brew install xctool
script:
  - xctool -workspace Example/TraceLog.xcworkspace -scheme TraceLog-Example -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES build test 
after_success:
  - bash <(curl -s https://codecov.io/bash)
