language: objective-c
xcode_workspace: Example/TraceLog.xcworkspace
xcode_scheme: TraceLog-Example
osx_image: xcode7.3

# "This temporarily uses xctool master in order to bypass facebook/xctool#684.", change this back to `brew install xctool` and revert the below script
before_install:
    - git clone https://github.com/facebook/xctool
    - gem install cocoapods --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent
    
script:
  - pod lib lint
  
  - xctool/xctool.sh -workspace Example/TraceLog.xcworkspace -scheme TraceLog-iOS-Example -sdk iphonesimulator test
  - xctool/xctool.sh -workspace Example/TraceLog.xcworkspace -scheme TraceLog-OSX-Example -sdk macosx test

after_success:
  - bash <(curl -s https://codecov.io/bash)
