language: swift
os: osx
osx_image: xcode8

before_install:
    - gem install xcpretty -N --no-ri --no-rdoc

env:
    matrix:
        - MATRIX_TARGET="-scheme TraceLog-iOS-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'"
        - MATRIX_TARGET="-scheme TraceLog-OSX-Example -sdk macosx"


script:
    - set -o pipefail
    - xcodebuild clean test -workspace Example/TraceLog.xcworkspace $MATRIX_TARGET GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)
