language: objective-c
xcode_workspace: Example/TraceLog.xcworkspace
xcode_scheme: TraceLog-Example
osx_image: xcode7.2

before_install:
    - brew install xctool
    - gem install cocoapods --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent
    
script:
  - pod lib lint
  
  - xctool -workspace Example/TraceLog.xcworkspace -scheme TraceLog-iOS-Example -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES test
  - xctool -workspace Example/TraceLog.xcworkspace -scheme TraceLog-OSX-Example -sdk macosx GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES test
  - xctool -workspace Example/TraceLog.xcworkspace -scheme "TraceLog-WatchOS - Notification Extension" -sdk watchos GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES build

after_success:
  - bash <(curl -s https://codecov.io/bash)
