

comment:
  layout: header, changes, diff, tree
coverage:
  ignore:
    - Example/.*
    - Scripts/.*
    - Docs/.*
    - Tests/.*
    - Pods/.*
    - Applications/Xcode.app/.*
    - vendor/.*
    - Carthage/.*
    - build/.*
    - .build/.*
    - .vagrant/.*

  status:
    patch: false


